local colorscheme = require("butbicket.colorscheme")
local config = require("butbicket.config")
local utils = require("butbicket.utils")
local bg = config.transparent and "NONE" or colorscheme.editorBackground
local diff_text =
  utils.shade(colorscheme.diffTextBase, 0.5, colorscheme.editorBackground)

return {
  Normal = { fg = colorscheme.mainText, bg = bg },
  LineNr = { fg = colorscheme.lineNumberText },
  ColorColumn = {
    bg = utils.shade(colorscheme.linkText, 0.5, colorscheme.editorBackground),
  },
  Added = { fg = colorscheme.added_bright },
  Changed = { fg = colorscheme.changed_bright },
  Removed = { fg = colorscheme.removed_bright },
  Conceal = {},
  Cursor = { fg = colorscheme.editorBackground, bg = colorscheme.mainText },
  lCursor = { link = "Cursor" },
  CursorIM = { link = "Cursor" },
  CursorLine = { bg = colorscheme.popupBackground },
  CursorColumn = { link = "CursorLine" },
  Directory = { fg = colorscheme.syntaxFunction },
  DiffAdd = { bg = colorscheme.added_dim },
  DiffChange = { bg = colorscheme.changed_dim },
  DiffDelete = { bg = colorscheme.removed_dim },
  -- GitSigns groups now live in integrations/gitsigns.lua (auto-gated).
  DiffText = { bg = diff_text },
  EndOfBuffer = { fg = colorscheme.syntaxKeyword },
  TermCursor = { link = "Cursor" },
  TermCursorNC = { link = "Cursor" },
  ErrorMsg = { fg = colorscheme.syntaxError },
  VertSplit = { fg = colorscheme.windowBorder, bg = bg },
  Winseparator = { link = "VertSplit" },
  SignColumn = { link = "Normal" },
  Folded = { fg = colorscheme.mainText, bg = colorscheme.base_2 },
  FoldColumn = { link = "SignColumn" },
  IncSearch = {
    bg = utils.mix(
      colorscheme.incSearchBase,
      colorscheme.editorBackground,
      0.30
    ),
  },
  Substitute = { link = "IncSearch" },
  CursorLineNr = { fg = colorscheme.dark_slate },
  MatchParen = { fg = colorscheme.hotpink, bold = true },
  ModeMsg = { link = "Normal" },
  MsgArea = { link = "Normal" },
  MsgSeparator = { link = "VertSplit" },
  MoreMsg = { fg = colorscheme.syntaxFunction },
  NonText = { fg = utils.shade(colorscheme.editorBackground, 0.75) },
  NormalFloat = { bg = colorscheme.floatingWindowBackground },
  FloatBorder = {
    bg = colorscheme.floatingWindowBackground,
    fg = colorscheme.floatBorder,
  },
  PmenuBorder = {
    bg = colorscheme.floatingWindowBackground,
    fg = colorscheme.floatBorder,
  },
  NormalNC = { link = "Normal" },
  Pmenu = { link = "NormalFloat" },
  PmenuSel = { bg = colorscheme.menuOptionBackground },
  PmenuSbar = {
    bg = utils.shade(
      colorscheme.floatBorder,
      0.5,
      colorscheme.editorBackground
    ),
  },
  PmenuThumb = { bg = utils.shade(colorscheme.editorBackground, 0.20) },
  Question = { fg = colorscheme.syntaxFunction },
  QuickFixLine = { bg = colorscheme.cursorline },
  SpecialKey = { fg = colorscheme.syntaxOperator },
  StatusLine = { fg = colorscheme.mainText, bg = colorscheme.windowBorder },
  StatusLineNC = {
    bg = colorscheme.sidebarBackground,
    fg = colorscheme.slate_gray,
  },
  TabLine = { bg = colorscheme.dark_slate, fg = colorscheme.steel_gray },
  TabLineFill = { bg = colorscheme.windowBorder },
  TabLineSel = {
    bg = colorscheme.slate,
    fg = colorscheme.text_dark,
    bold = true,
  },
  Search = {
    bg = utils.mix(colorscheme.searchBase, colorscheme.editorBackground, 0.4),
  },
  CurSearch = {
    bg = utils.mix(colorscheme.searchBase, colorscheme.editorBackground, 0.8),
  },
  SpellBad = { undercurl = true, sp = colorscheme.syntaxError },
  SpellCap = { undercurl = true, sp = colorscheme.syntaxFunction },
  SpellLocal = { undercurl = true, sp = colorscheme.syntaxKeyword },
  SpellRare = { undercurl = true, sp = colorscheme.warningText },
  Title = { fg = colorscheme.syntaxFunction },
  Visual = { bg = colorscheme.menuOptionBackground },
  VisualNOS = { link = "Visual" },
  WarningMsg = { fg = colorscheme.warningText },
  Whitespace = { fg = colorscheme.syntaxOperator },
  WildMenu = { bg = colorscheme.menuOptionBackground },
  Comment = {
    fg = colorscheme.commentText,
    italic = config.italics.comments or false,
  },
  Dimmed = { fg = colorscheme.dark_charcoal },
  SpecialComment = { fg = colorscheme.commentText },
  Constant = { fg = colorscheme.syntaxError },
  String = {
    fg = colorscheme.stringText,
    italic = config.italics.strings or false,
  },
  Character = { fg = colorscheme.stringText },
  Number = { fg = colorscheme.syntaxNumber },
  Boolean = { fg = colorscheme.syntaxKeyword },
  Float = { link = "Number" },
  Identifier = { fg = colorscheme.steel_gray },
  Function = { fg = colorscheme.syntaxFunction },
  Method = { fg = colorscheme.syntaxFunction },
  Property = { fg = colorscheme.text_dark },
  Field = { link = "Property" },
  Parameter = { fg = colorscheme.parameter },
  Statement = {
    fg = colorscheme.keyword,
    bold = true,
    italic = config.italics.statements or false,
  },
  Conditional = { fg = colorscheme.syntaxError },
  Label = { fg = colorscheme.syntaxFunction },
  Operator = { fg = colorscheme.syntaxOperator, bold = true },
  Keyword = {
    link = "Statement",
    italic = config.italics.keywords or false,
    bold = true,
  },
  Exception = { fg = colorscheme.syntaxError },
  PreProc = { link = "Keyword" },
  Define = { fg = colorscheme.syntaxKeyword },
  Macro = { link = "Define" },
  PreCondit = { fg = colorscheme.selected },
  Type = { fg = colorscheme.type },
  Struct = { link = "Type" },
  Class = { link = "Type" },
  Attribute = { link = "Character" },
  Punctuation = { fg = colorscheme.light_red },
  Special = { fg = colorscheme.syntaxOperator },
  SpecialChar = { fg = colorscheme.syntaxError },
  Tag = { fg = colorscheme.blue },
  Delimiter = { fg = colorscheme.syntaxOperator },
  Debug = { fg = colorscheme.specialKeyword },
  Underlined = { underline = true },
  Bold = { bold = true },
  Italic = { italic = true },
  Ignore = { fg = colorscheme.editorBackground },
  Error = { link = "ErrorMsg" },
  Todo = { fg = colorscheme.warningText, bold = true },
  DiagnosticError = { link = "Error" },
  DiagnosticWarn = { link = "WarningMsg" },
  DiagnosticInfo = { fg = colorscheme.blue },
  DiagnosticHint = { fg = colorscheme.method },
  DiagnosticVirtualTextError = { link = "DiagnosticError" },
  DiagnosticVirtualTextWarn = { link = "DiagnosticWarn" },
  DiagnosticVirtualTextInfo = { link = "DiagnosticInfo" },
  DiagnosticVirtualTextHint = { link = "DiagnosticHint" },
  DiagnosticUnderlineError = { undercurl = true, fg = colorscheme.syntaxError },
  DiagnosticUnderlineWarn = { undercurl = true, fg = colorscheme.warningText },
  DiagnosticUnderlineInfo = { undercurl = true, fg = colorscheme.blue },
  DiagnosticUnderlineHint = { undercurl = true, fg = colorscheme.method },
  DiagnosticLineError = {
    bg = utils.shade(
      colorscheme.syntaxError,
      0.1,
      colorscheme.editorBackground
    ),
  },
  DiagnosticLineWarn = {
    bg = utils.shade(
      colorscheme.warningText,
      0.1,
      colorscheme.editorBackground
    ),
  },
  DiagnosticLineInfo = {
    bg = utils.shade(colorscheme.blue, 0.1, colorscheme.editorBackground),
  },
  DiagnosticLineHint = {
    bg = utils.shade(colorscheme.method, 0.1, colorscheme.editorBackground),
  },
  -- treesitter-context, neo-tree and lazy groups now live in their own
  -- auto-gated integration modules.
  ["@text"] = { fg = colorscheme.mainText },
  ["@markup"] = { fg = colorscheme.mainText },
  ["@markup.raw"] = { link = "Property" },
  ["@markup.strong"] = { link = "Bold" },
  ["@markup.italic"] = { link = "Italic" },
  ["@markup.heading"] = { link = "Keyword" },
  ["@markup.link"] = {
    fg = colorscheme.syntaxFunction,
    sp = colorscheme.syntaxFunction,
    underline = true,
  },
  ["@markup.link.url"] = { link = "@markup.link" },
  ["@markup.underline"] = { link = "Underlined" },
  ["@symbol"] = { fg = colorscheme.syntaxOperator },
  ["@comment.todo"] = { link = "Todo" },
  ["@comment"] = { link = "Comment" },
  ["@punctuation"] = { link = "Punctuation" },
  ["@punctuation.bracket"] = { link = "Punctuation" }, -- fg = colorscheme.warningEmphasis },
  ["@punctuation.bracket.css"] = { fg = colorscheme.purple }, -- fg = colorscheme.warningEmphasis },
  ["@punctuation.bracket.scss"] = { fg = colorscheme.purple }, -- fg = colorscheme.warningEmphasis },
  ["@punctuation.delimiter"] = { link = "Punctuation" }, -- fg = colorscheme.syntaxError },
  ["@punctuation.terminator.statement"] = { link = "Delimiter" },
  ["@punctuation.special"] = { fg = colorscheme.syntaxError },
  ["@punctuation.separator.keyvalue"] = { link = "Punctuation" }, -- { fg = colorscheme.syntaxError },
  ["@diff.plus"] = { bg = colorscheme.added },
  ["@diff.minus"] = { bg = colorscheme.removed },
  ["@constant"] = { link = "Constant" },
  ["@constant.builtin"] = { fg = colorscheme.syntaxFunction },
  ["@string"] = { link = "String" },
  ["@string.vue"] = { fg = colorscheme.light_red },
  ["@string.html"] = { fg = colorscheme.light_red },
  ["@string.escape"] = { fg = utils.shade(colorscheme.stringText, 0.45) },
  ["@string.special"] = { fg = utils.shade(colorscheme.syntaxFunction, 0.45) },
  ["@number"] = { link = "Number" },
  ["@boolean"] = { link = "Boolean" },
  ["@function"] = {
    link = "Function",
    italic = config.italics.functions or false,
  },
  ["@function.call"] = { link = "Function" },
  ["@function.builtin"] = { link = "Function" },
  ["@parameter"] = { link = "Parameter" },
  ["@method"] = { link = "Function" },
  ["@field"] = { link = "Property" },
  ["@property"] = { link = "Property" },
  ["@constructor"] = { fg = colorscheme.syntaxFunction },
  ["@label"] = { link = "Label" },
  ["@operator"] = { link = "Operator" },
  ["@exception"] = { link = "Exception" },
  ["@variable"] = {
    fg = colorscheme.variable,
    italic = config.italics.variables or false,
  },
  ["@variable.builtin"] = { fg = colorscheme.emphasisText },
  ["@variable.member"] = {
    fg = colorscheme.variable_member,
    italic = config.italics.variable_members or false,
  },
  ["@variable.parameter"] = {
    fg = colorscheme.parameter,
    italic = config.italics.variable_parameters or false,
  },
  ["@type"] = { link = "Type" },
  ["@type.definition"] = { fg = colorscheme.variable },
  ["@type.builtin"] = { fg = colorscheme.syntaxFunction },
  ["@type.qualifier"] = { fg = colorscheme.syntaxFunction },
  ["@keyword"] = { link = "Keyword" },
  ["@namespace"] = { link = "Type" },
  ["@annotation"] = { link = "Label" },
  ["@debug"] = { fg = colorscheme.specialKeyword },
  ["@tag"] = { link = "Tag" },
  ["@tag.builtin"] = { link = "Tag" },
  ["@tag.delimiter"] = { fg = colorscheme.syntaxOperator },
  ["@tag.attribute"] = { fg = colorscheme.method },
  ["@tag.jsx.element"] = { fg = colorscheme.syntaxFunction },
  ["@attribute"] = { fg = colorscheme.selected },
  ["@error"] = { link = "Error" },
  ["@warning"] = { link = "WarningMsg" },
  ["@info"] = { fg = colorscheme.syntaxFunction },
  ["@label.json"] = { link = "Property" }, -- For json
  ["@label.help"] = { link = "@markup.link" }, -- For help files
  ["@markup.link.html"] = { underline = true }, -- For html
  ["@lsp.type.namespace"] = { link = "@namespace" },
  ["@lsp.type.type"] = { link = "@type" },
  ["@lsp.type.class"] = { link = "@type" },
  ["@lsp.type.enum"] = { link = "@type" },
  ["@lsp.type.enumMember"] = { fg = colorscheme.syntaxFunction },
  ["@lsp.type.interface"] = { link = "@type" },
  ["@lsp.type.struct"] = { link = "@type" },
  ["@lsp.type.parameter"] = { link = "@parameter" },
  ["@lsp.type.property"] = { link = "@text" },
  ["@lsp.type.function"] = { link = "@function" },
  ["@lsp.type.method"] = { link = "@method" },
  ["@lsp.type.macro"] = { link = "@label" },
  ["@lsp.type.decorator"] = { link = "@label" },
  ["@lsp.typemod.function.declaration"] = { link = "@function" },
  ["@lsp.typemod.function.readonly"] = { link = "@function" },
}
