-- Terminal-emulator theme emitters (Ghostty, Kitty, Alacritty, WezTerm, Warp).
-- Each takes the collected palette table `t` (see extras/init.lua `collect`) and
-- returns `{ ext = <file extension>, body = <file contents> }`.

local M = {}

-- ANSI slot names, index 0..7 (bright reuse the same names).
local names = {
  [0] = "black",
  [1] = "red",
  [2] = "green",
  [3] = "yellow",
  [4] = "blue",
  [5] = "magenta",
  [6] = "cyan",
  [7] = "white",
}

local function join(t, sep)
  return table.concat(t, sep)
end

M.ghostty = function(t)
  local l =
    { "# " .. t.name .. " — generated by scripts/gen-terminals.lua", "" }
  table.insert(l, "# normal colors")
  for i = 0, 7 do
    table.insert(l, ("palette = %d=%s"):format(i, t.ansi[i]))
  end
  table.insert(l, "")
  table.insert(l, "# bright colors")
  for i = 8, 15 do
    table.insert(l, ("palette = %d=%s"):format(i, t.ansi[i]))
  end
  table.insert(l, "")
  table.insert(l, "background = " .. t.bg)
  table.insert(l, "foreground = " .. t.fg)
  table.insert(l, "cursor-color = " .. t.cursor)
  table.insert(l, "")
  table.insert(l, "selection-background = " .. t.sel_bg)
  table.insert(l, "selection-foreground = " .. t.sel_fg)
  return { ext = "", body = join(l, "\n") .. "\n" }
end

M.kitty = function(t)
  local l =
    { "# " .. t.name .. " — generated by scripts/gen-terminals.lua", "" }
  table.insert(l, "foreground " .. t.fg)
  table.insert(l, "background " .. t.bg)
  table.insert(l, "cursor " .. t.cursor)
  table.insert(l, "cursor_text_color " .. t.bg)
  table.insert(l, "selection_background " .. t.sel_bg)
  table.insert(l, "selection_foreground " .. t.sel_fg)
  table.insert(l, "")
  for i = 0, 15 do
    table.insert(l, ("color%d %s"):format(i, t.ansi[i]))
  end
  return { ext = ".conf", body = join(l, "\n") .. "\n" }
end

M.alacritty = function(t)
  local l =
    { "# " .. t.name .. " — generated by scripts/gen-terminals.lua", "" }
  table.insert(l, "[colors.primary]")
  table.insert(l, ('background = "%s"'):format(t.bg))
  table.insert(l, ('foreground = "%s"'):format(t.fg))
  table.insert(l, "")
  table.insert(l, "[colors.cursor]")
  table.insert(l, ('text = "%s"'):format(t.bg))
  table.insert(l, ('cursor = "%s"'):format(t.cursor))
  table.insert(l, "")
  table.insert(l, "[colors.selection]")
  table.insert(l, ('text = "%s"'):format(t.sel_fg))
  table.insert(l, ('background = "%s"'):format(t.sel_bg))
  for _, block in ipairs({ { "normal", 0 }, { "bright", 8 } }) do
    table.insert(l, "")
    table.insert(l, ("[colors.%s]"):format(block[1]))
    for i = 0, 7 do
      table.insert(l, ('%s = "%s"'):format(names[i], t.ansi[block[2] + i]))
    end
  end
  return { ext = ".toml", body = join(l, "\n") .. "\n" }
end

M.wezterm = function(t)
  local function arr(from)
    local q = {}
    for i = from, from + 7 do
      table.insert(q, ('"%s"'):format(t.ansi[i]))
    end
    return "[" .. join(q, ", ") .. "]"
  end
  local l =
    { "# " .. t.name .. " — generated by scripts/gen-terminals.lua", "" }
  table.insert(l, "[colors]")
  table.insert(l, ('foreground = "%s"'):format(t.fg))
  table.insert(l, ('background = "%s"'):format(t.bg))
  table.insert(l, ('cursor_bg = "%s"'):format(t.cursor))
  table.insert(l, ('cursor_fg = "%s"'):format(t.bg))
  table.insert(l, ('cursor_border = "%s"'):format(t.cursor))
  table.insert(l, ('selection_bg = "%s"'):format(t.sel_bg))
  table.insert(l, ('selection_fg = "%s"'):format(t.sel_fg))
  table.insert(l, ("ansi = %s"):format(arr(0)))
  table.insert(l, ("brights = %s"):format(arr(8)))
  table.insert(l, "")
  table.insert(l, "[metadata]")
  table.insert(l, ('name = "%s"'):format(t.name))
  table.insert(l, 'author = "svampkorg"')
  return { ext = ".toml", body = join(l, "\n") .. "\n" }
end

M.warp = function(t)
  local l = { "# " .. t.name .. " — generated by scripts/gen-terminals.lua" }
  table.insert(l, ('accent: "%s"'):format(t.accent))
  table.insert(l, ('background: "%s"'):format(t.bg))
  table.insert(l, ('foreground: "%s"'):format(t.fg))
  table.insert(l, ("details: %s"):format(t.light and "lighter" or "darker"))
  table.insert(l, "terminal_colors:")
  for _, block in ipairs({ { "normal", 0 }, { "bright", 8 } }) do
    table.insert(l, ("  %s:"):format(block[1]))
    for i = 0, 7 do
      table.insert(l, ('    %s: "%s"'):format(names[i], t.ansi[block[2] + i]))
    end
  end
  return { ext = ".yaml", body = join(l, "\n") .. "\n" }
end

return M
