-- Generate terminal theme files from the butbicket palette.
--
-- Usage:
--   nvim -l scripts/gen-terminals.lua           # all terminals, both variants
--   nvim -l scripts/gen-terminals.lua dark      # both terminals, one variant
--   nvim -l scripts/gen-terminals.lua dark kitty # one variant, one terminal
--
-- The 16 ANSI slots are read back from `vim.g.terminal_color_*` after applying
-- the colorscheme, so every file matches what Neovim's :terminal uses —
-- set_terminal_colors() in init.lua stays the single source of truth.

package.path = './lua/?.lua;./lua/?/init.lua;' .. package.path

local function upper(hex)
  return (hex or ''):upper()
end

-- Apply a variant and collect everything the emitters need.
local function collect(background)
  vim.o.background = background
  require('butbicket').colorscheme()

  package.loaded['butbicket.colorscheme'] = nil
  local c = require 'butbicket.colorscheme'

  local ansi = {}
  for i = 0, 15 do
    ansi[i] = upper(vim.g['terminal_color_' .. i])
  end

  return {
    name = 'butbicket-' .. background,
    light = background == 'light',
    ansi = ansi, -- 0..15
    bg = upper(vim.g.terminal_color_background),
    fg = upper(vim.g.terminal_color_foreground),
    cursor = upper(c.mainText),
    sel_bg = upper(c.selected),
    sel_fg = upper(c.emphasisText),
    accent = upper(c.linkText),
  }
end

-- ANSI slot names, index 0..7 (bright reuse the same names).
local names = {
  [0] = 'black',
  [1] = 'red',
  [2] = 'green',
  [3] = 'yellow',
  [4] = 'blue',
  [5] = 'magenta',
  [6] = 'cyan',
  [7] = 'white',
}

local function join(t, sep)
  return table.concat(t, sep)
end

-- Each emitter: (t) -> { ext = string, body = string }
local emitters = {}

emitters.ghostty = function(t)
  local l = { '# ' .. t.name .. ' — generated by scripts/gen-terminals.lua', '' }
  table.insert(l, '# normal colors')
  for i = 0, 7 do
    table.insert(l, ('palette = %d=%s'):format(i, t.ansi[i]))
  end
  table.insert(l, '')
  table.insert(l, '# bright colors')
  for i = 8, 15 do
    table.insert(l, ('palette = %d=%s'):format(i, t.ansi[i]))
  end
  table.insert(l, '')
  table.insert(l, 'background = ' .. t.bg)
  table.insert(l, 'foreground = ' .. t.fg)
  table.insert(l, 'cursor-color = ' .. t.cursor)
  table.insert(l, '')
  table.insert(l, 'selection-background = ' .. t.sel_bg)
  table.insert(l, 'selection-foreground = ' .. t.sel_fg)
  return { ext = '', body = join(l, '\n') .. '\n' }
end

emitters.kitty = function(t)
  local l = { '# ' .. t.name .. ' — generated by scripts/gen-terminals.lua', '' }
  table.insert(l, 'foreground ' .. t.fg)
  table.insert(l, 'background ' .. t.bg)
  table.insert(l, 'cursor ' .. t.cursor)
  table.insert(l, 'cursor_text_color ' .. t.bg)
  table.insert(l, 'selection_background ' .. t.sel_bg)
  table.insert(l, 'selection_foreground ' .. t.sel_fg)
  table.insert(l, '')
  for i = 0, 15 do
    table.insert(l, ('color%d %s'):format(i, t.ansi[i]))
  end
  return { ext = '.conf', body = join(l, '\n') .. '\n' }
end

emitters.alacritty = function(t)
  local l = { '# ' .. t.name .. ' — generated by scripts/gen-terminals.lua', '' }
  table.insert(l, '[colors.primary]')
  table.insert(l, ('background = "%s"'):format(t.bg))
  table.insert(l, ('foreground = "%s"'):format(t.fg))
  table.insert(l, '')
  table.insert(l, '[colors.cursor]')
  table.insert(l, ('text = "%s"'):format(t.bg))
  table.insert(l, ('cursor = "%s"'):format(t.cursor))
  table.insert(l, '')
  table.insert(l, '[colors.selection]')
  table.insert(l, ('text = "%s"'):format(t.sel_fg))
  table.insert(l, ('background = "%s"'):format(t.sel_bg))
  for _, block in ipairs { { 'normal', 0 }, { 'bright', 8 } } do
    table.insert(l, '')
    table.insert(l, ('[colors.%s]'):format(block[1]))
    for i = 0, 7 do
      table.insert(l, ('%s = "%s"'):format(names[i], t.ansi[block[2] + i]))
    end
  end
  return { ext = '.toml', body = join(l, '\n') .. '\n' }
end

emitters.wezterm = function(t)
  local function arr(from)
    local q = {}
    for i = from, from + 7 do
      table.insert(q, ('"%s"'):format(t.ansi[i]))
    end
    return '[' .. join(q, ', ') .. ']'
  end
  local l = { '# ' .. t.name .. ' — generated by scripts/gen-terminals.lua', '' }
  table.insert(l, '[colors]')
  table.insert(l, ('foreground = "%s"'):format(t.fg))
  table.insert(l, ('background = "%s"'):format(t.bg))
  table.insert(l, ('cursor_bg = "%s"'):format(t.cursor))
  table.insert(l, ('cursor_fg = "%s"'):format(t.bg))
  table.insert(l, ('cursor_border = "%s"'):format(t.cursor))
  table.insert(l, ('selection_bg = "%s"'):format(t.sel_bg))
  table.insert(l, ('selection_fg = "%s"'):format(t.sel_fg))
  table.insert(l, ('ansi = %s'):format(arr(0)))
  table.insert(l, ('brights = %s'):format(arr(8)))
  table.insert(l, '')
  table.insert(l, '[metadata]')
  table.insert(l, ('name = "%s"'):format(t.name))
  table.insert(l, 'author = "svampkorg"')
  return { ext = '.toml', body = join(l, '\n') .. '\n' }
end

emitters.warp = function(t)
  local l = { '# ' .. t.name .. ' — generated by scripts/gen-terminals.lua' }
  table.insert(l, ('accent: "%s"'):format(t.accent))
  table.insert(l, ('background: "%s"'):format(t.bg))
  table.insert(l, ('foreground: "%s"'):format(t.fg))
  table.insert(l, ('details: %s'):format(t.light and 'lighter' or 'darker'))
  table.insert(l, 'terminal_colors:')
  for _, block in ipairs { { 'normal', 0 }, { 'bright', 8 } } do
    table.insert(l, ('  %s:'):format(block[1]))
    for i = 0, 7 do
      table.insert(
        l,
        ('    %s: "%s"'):format(names[i], t.ansi[block[2] + i])
      )
    end
  end
  return { ext = '.yaml', body = join(l, '\n') .. '\n' }
end

local function write(path, contents)
  vim.fn.mkdir(vim.fn.fnamemodify(path, ':h'), 'p')
  local fd = assert(io.open(path, 'w'))
  fd:write(contents)
  fd:close()
  print('wrote ' .. path)
end

local variants = arg[1] and { arg[1] } or { 'dark', 'light' }
local terminals = arg[2] and { arg[2] }
  or { 'ghostty', 'kitty', 'alacritty', 'wezterm', 'warp' }

for _, v in ipairs(variants) do
  local t = collect(v)
  for _, term in ipairs(terminals) do
    local emit = emitters[term]
    if not emit then
      error('unknown terminal: ' .. term)
    end
    local out = emit(t)
    write(('extras/%s/%s%s'):format(term, t.name, out.ext), out.body)
  end
end
