-- Generate terminal theme files from the butbicket palette.
--
-- Usage:
--   nvim -l scripts/gen-terminals.lua           # all terminals, both variants
--   nvim -l scripts/gen-terminals.lua dark      # both terminals, one variant
--   nvim -l scripts/gen-terminals.lua dark kitty # one variant, one terminal
--
-- The 16 ANSI slots are read back from `vim.g.terminal_color_*` after applying
-- the colorscheme, so every file matches what Neovim's :terminal uses —
-- set_terminal_colors() in init.lua stays the single source of truth.

package.path = "./lua/?.lua;./lua/?/init.lua;" .. package.path

local function upper(hex)
  return (hex or ""):upper()
end

-- Apply a variant and collect everything the emitters need.
local function collect(background)
  vim.o.background = background
  require("butbicket").colorscheme()

  package.loaded["butbicket.colorscheme"] = nil
  local c = require("butbicket.colorscheme")

  local ansi = {}
  for i = 0, 15 do
    ansi[i] = upper(vim.g["terminal_color_" .. i])
  end

  return {
    name = "butbicket-" .. background,
    light = background == "light",
    ansi = ansi, -- 0..15
    bg = upper(vim.g.terminal_color_background),
    fg = upper(vim.g.terminal_color_foreground),
    cursor = upper(c.mainText),
    sel_bg = upper(c.selected),
    sel_fg = upper(c.emphasisText),
    accent = upper(c.linkText),

    -- syntax palette (bat .tmTheme)
    keyword = upper(c.keyword),
    string = upper(c.stringText),
    func = upper(c.syntaxFunction),
    number = upper(c.syntaxNumber or c.number),
    type = upper(c.type),
    variable = upper(c.variable),
    parameter = upper(c.parameter),
    comment = upper(c.commentText),
    operator = upper(c.syntaxOperator),
    boolean = upper(c.syntaxKeyword),
    punctuation = upper(c.light_red),
    tag = upper(c.linkText),
    attribute = upper(c.method),
    line_bg = upper(c.cursorline),

    -- ui / status / diffs (Claude Code custom theme)
    error = upper(c.errorText),
    warning = upper(c.warningText),
    success = upper(c.successText),
    purple = upper(c.purple),
    added = upper(c.added),
    removed = upper(c.removed),
    added_dim = upper(c.added_dim),
    removed_dim = upper(c.removed_dim),
    added_word = upper(c.added_bright),
    removed_word = upper(c.removed_bright),
    border = upper(c.windowBorder),
    focus_border = upper(c.focusedBorder),
    emph_border = upper(c.emphasizedBorder),
    inactive = upper(c.inactiveText),
  }
end

-- ANSI slot names, index 0..7 (bright reuse the same names).
local names = {
  [0] = "black",
  [1] = "red",
  [2] = "green",
  [3] = "yellow",
  [4] = "blue",
  [5] = "magenta",
  [6] = "cyan",
  [7] = "white",
}

local function join(t, sep)
  return table.concat(t, sep)
end

-- Each emitter: (t) -> { ext = string, body = string }
local emitters = {}

emitters.ghostty = function(t)
  local l =
    { "# " .. t.name .. " — generated by scripts/gen-terminals.lua", "" }
  table.insert(l, "# normal colors")
  for i = 0, 7 do
    table.insert(l, ("palette = %d=%s"):format(i, t.ansi[i]))
  end
  table.insert(l, "")
  table.insert(l, "# bright colors")
  for i = 8, 15 do
    table.insert(l, ("palette = %d=%s"):format(i, t.ansi[i]))
  end
  table.insert(l, "")
  table.insert(l, "background = " .. t.bg)
  table.insert(l, "foreground = " .. t.fg)
  table.insert(l, "cursor-color = " .. t.cursor)
  table.insert(l, "")
  table.insert(l, "selection-background = " .. t.sel_bg)
  table.insert(l, "selection-foreground = " .. t.sel_fg)
  return { ext = "", body = join(l, "\n") .. "\n" }
end

emitters.kitty = function(t)
  local l =
    { "# " .. t.name .. " — generated by scripts/gen-terminals.lua", "" }
  table.insert(l, "foreground " .. t.fg)
  table.insert(l, "background " .. t.bg)
  table.insert(l, "cursor " .. t.cursor)
  table.insert(l, "cursor_text_color " .. t.bg)
  table.insert(l, "selection_background " .. t.sel_bg)
  table.insert(l, "selection_foreground " .. t.sel_fg)
  table.insert(l, "")
  for i = 0, 15 do
    table.insert(l, ("color%d %s"):format(i, t.ansi[i]))
  end
  return { ext = ".conf", body = join(l, "\n") .. "\n" }
end

emitters.alacritty = function(t)
  local l =
    { "# " .. t.name .. " — generated by scripts/gen-terminals.lua", "" }
  table.insert(l, "[colors.primary]")
  table.insert(l, ('background = "%s"'):format(t.bg))
  table.insert(l, ('foreground = "%s"'):format(t.fg))
  table.insert(l, "")
  table.insert(l, "[colors.cursor]")
  table.insert(l, ('text = "%s"'):format(t.bg))
  table.insert(l, ('cursor = "%s"'):format(t.cursor))
  table.insert(l, "")
  table.insert(l, "[colors.selection]")
  table.insert(l, ('text = "%s"'):format(t.sel_fg))
  table.insert(l, ('background = "%s"'):format(t.sel_bg))
  for _, block in ipairs({ { "normal", 0 }, { "bright", 8 } }) do
    table.insert(l, "")
    table.insert(l, ("[colors.%s]"):format(block[1]))
    for i = 0, 7 do
      table.insert(l, ('%s = "%s"'):format(names[i], t.ansi[block[2] + i]))
    end
  end
  return { ext = ".toml", body = join(l, "\n") .. "\n" }
end

emitters.wezterm = function(t)
  local function arr(from)
    local q = {}
    for i = from, from + 7 do
      table.insert(q, ('"%s"'):format(t.ansi[i]))
    end
    return "[" .. join(q, ", ") .. "]"
  end
  local l =
    { "# " .. t.name .. " — generated by scripts/gen-terminals.lua", "" }
  table.insert(l, "[colors]")
  table.insert(l, ('foreground = "%s"'):format(t.fg))
  table.insert(l, ('background = "%s"'):format(t.bg))
  table.insert(l, ('cursor_bg = "%s"'):format(t.cursor))
  table.insert(l, ('cursor_fg = "%s"'):format(t.bg))
  table.insert(l, ('cursor_border = "%s"'):format(t.cursor))
  table.insert(l, ('selection_bg = "%s"'):format(t.sel_bg))
  table.insert(l, ('selection_fg = "%s"'):format(t.sel_fg))
  table.insert(l, ("ansi = %s"):format(arr(0)))
  table.insert(l, ("brights = %s"):format(arr(8)))
  table.insert(l, "")
  table.insert(l, "[metadata]")
  table.insert(l, ('name = "%s"'):format(t.name))
  table.insert(l, 'author = "svampkorg"')
  return { ext = ".toml", body = join(l, "\n") .. "\n" }
end

emitters.warp = function(t)
  local l = { "# " .. t.name .. " — generated by scripts/gen-terminals.lua" }
  table.insert(l, ('accent: "%s"'):format(t.accent))
  table.insert(l, ('background: "%s"'):format(t.bg))
  table.insert(l, ('foreground: "%s"'):format(t.fg))
  table.insert(l, ("details: %s"):format(t.light and "lighter" or "darker"))
  table.insert(l, "terminal_colors:")
  for _, block in ipairs({ { "normal", 0 }, { "bright", 8 } }) do
    table.insert(l, ("  %s:"):format(block[1]))
    for i = 0, 7 do
      table.insert(l, ('    %s: "%s"'):format(names[i], t.ansi[block[2] + i]))
    end
  end
  return { ext = ".yaml", body = join(l, "\n") .. "\n" }
end

-- Claude Code custom theme (~/.claude/themes/<name>.json). Controls UI chrome
-- only — diffs, borders, status, accent — NOT code syntax highlighting (that is
-- bat's job; see the `bat` emitter). Unknown/invalid override keys are ignored.
emitters["claude-code"] = function(t)
  local overrides = {
    { "claude", t.accent },
    { "text", t.fg },
    { "inverseText", t.bg },
    { "inactive", t.inactive },
    { "subtle", t.border },
    { "suggestion", t.comment },
    { "permission", t.emph_border },
    { "planMode", t.purple },
    { "autoAccept", t.success },
    { "bashBorder", t.operator },
    { "promptBorder", t.focus_border },
    { "success", t.success },
    { "error", t.error },
    { "warning", t.warning },
    { "diffAdded", t.added },
    { "diffRemoved", t.removed },
    { "diffAddedDimmed", t.added_dim },
    { "diffRemovedDimmed", t.removed_dim },
    { "diffAddedWord", t.added_word },
    { "diffRemovedWord", t.removed_word },
  }
  local lines = {}
  for i, kv in ipairs(overrides) do
    lines[i] = ('    "%s": "%s"%s'):format(
      kv[1],
      kv[2],
      i < #overrides and "," or ""
    )
  end
  local body = table.concat({
    "{",
    ('  "name": "%s",'):format(t.name),
    ('  "base": "%s",'):format(t.light and "light" or "dark"),
    '  "overrides": {',
    join(lines, "\n"),
    "  }",
    "}",
    "",
  }, "\n")
  return { ext = ".json", body = body }
end

-- bat / Sublime .tmTheme for CODE SYNTAX highlighting. Claude Code renders code
-- via bat, reading the theme name from CLAUDE_CODE_SYNTAX_HIGHLIGHT (or
-- BAT_THEME). Install into `$(bat --config-dir)/themes/`, run `bat cache
-- --build`, then set that env var to the theme name.
emitters.bat = function(t)
  local function settings(kvs)
    local out = {}
    for _, kv in ipairs(kvs) do
      out[#out + 1] = ("        <key>%s</key>\n        <string>%s</string>"):format(
        kv[1],
        kv[2]
      )
    end
    return join(out, "\n")
  end

  local function entry(scope, kvs)
    local head = scope
        and ("      <key>scope</key>\n      <string>%s</string>\n"):format(
          scope
        )
      or ""
    return table.concat({
      "    <dict>",
      head .. "      <key>settings</key>",
      "      <dict>",
      settings(kvs),
      "      </dict>",
      "    </dict>",
    }, "\n")
  end

  -- scope -> color (+ optional fontStyle)
  local scopes = {
    { "comment", t.comment, "italic" },
    { "string", t.string },
    { "constant.numeric", t.number },
    { "constant.language", t.boolean },
    { "constant.character.escape", t.string },
    { "keyword, storage, storage.type, keyword.control", t.keyword, "italic" },
    {
      "keyword.operator, punctuation.separator, punctuation.terminator",
      t.operator,
    },
    {
      "entity.name.function, support.function, meta.function-call",
      t.func,
    },
    { "variable, variable.other, meta.variable", t.variable },
    { "variable.parameter", t.parameter },
    {
      "entity.name.type, entity.name.class, support.type, support.class",
      t.type,
    },
    { "entity.name.tag", t.tag },
    { "entity.other.attribute-name", t.attribute },
    -- NOTE: no broad `punctuation.definition` rule — it out-specifies `comment`
    -- and `string` (whose delimiters inherit punctuation.definition.*) and would
    -- recolour them. Brackets fall to foreground, matching the Neovim look.
    { "invalid, invalid.illegal", t.error },
  }

  local entries = {
    entry(nil, {
      { "background", t.bg },
      { "foreground", t.fg },
      { "caret", t.cursor },
      { "selection", t.sel_bg },
      { "lineHighlight", t.line_bg },
    }),
  }
  for _, sc in ipairs(scopes) do
    local kvs = { { "foreground", sc[2] } }
    if sc[3] then
      kvs[#kvs + 1] = { "fontStyle", sc[3] }
    end
    entries[#entries + 1] = entry(sc[1], kvs)
  end

  local body = table.concat({
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
    '<plist version="1.0">',
    "<dict>",
    "  <key>name</key>",
    ("  <string>%s</string>"):format(t.name),
    "  <key>settings</key>",
    "  <array>",
    join(entries, "\n"),
    "  </array>",
    "</dict>",
    "</plist>",
    "",
  }, "\n")
  return { ext = ".tmTheme", body = body }
end

local function write(path, contents)
  vim.fn.mkdir(vim.fn.fnamemodify(path, ":h"), "p")
  local fd = assert(io.open(path, "w"))
  fd:write(contents)
  fd:close()
  print("wrote " .. path)
end

local variants = arg[1] and { arg[1] } or { "dark", "light" }
local terminals = arg[2] and { arg[2] }
  or { "ghostty", "kitty", "alacritty", "wezterm", "warp", "claude-code", "bat" }

for _, v in ipairs(variants) do
  local t = collect(v)
  for _, term in ipairs(terminals) do
    local emit = emitters[term]
    if not emit then
      error("unknown terminal: " .. term)
    end
    local out = emit(t)
    write(("extras/%s/%s%s"):format(term, t.name, out.ext), out.body)
  end
end
